### ISSUE TITLE
Test kitchen failing with error Chef::ChefFS::FileSystem::NotFoundError

### ISSUE THREAD

**Issue by AReshma** [AReshma/amhser#1]
I am running a cookbook in test kitchen using docker. The cookbook is failing with below error.

[2015-03-10T07:44:39+00:00] ERROR: #< Chef::ChefFS::FileSystem::NotFoundError: Chef::ChefFS::FileSystem::NotFoundError >
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system/chef_repository_file_system_cookbooks_dir.rb:54:in `rescue in children'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system/chef_repository_file_system_cookbooks_dir.rb:40:in `children'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system/multiplexed_dir.rb:25:in `block in children'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system/multiplexed_dir.rb:24:in `each'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system/multiplexed_dir.rb:24:in `children'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system/base_fs_dir.rb:36:in `child'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system.rb:105:in `block in resolve_path'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system.rb:104:in `each'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/file_system.rb:104:in `resolve_path'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2/lib/chef/chef_fs/chef_fs_data_store.rb:83:in `get'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:66:in `block in get'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:168:in `fix_exceptions'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:65:in `get'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/rest_base.rb:43:in `get_data'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/endpoints/file_store_file_endpoint.rb:13:in `get'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/rest_base.rb:29:in `call'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/rest_router.rb:23:in `call'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.2/lib/chef_zero/server.rb:443:in `block in app'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
       /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
       /opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
       /opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
       /opt/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
                
           ================================================================================
           Error executing action `create` on resource 'template[/etc/sysconfig/selinux]'
           ================================================================================
           
           Net::HTTPFatalError
           -------------------
           500 "Internal Server Error "
           
           ---------------------
                     
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mytest/definitions/disable_selinux.rb:4:in `block in from_file'
           
           template("/etc/sysconfig/selinux") do
             params {:name=>nil}
             provider Chef::Provider::Template
             action "create"
             retries 0
             retry_delay 2
             guard_interpreter :default
             path "/etc/sysconfig/selinux"
             backup 5
             atomic_update true
             source "selinux-6.erb"
             cookbook_name "mytest"
             recipe_name "selinux_policy"
             mode 420
             owner "root"
             only_if { #code block }
           end

The template file name is correct, and I am able to see the file inside /template folder. I have a number of recipes running before the recipe which is failing.
I tried by changing the run list to run the failed recipe alone, and it is working.
How to resolve this.

Thanks

**Comment by juozasg** [comment]
Hi Reshma,

This is a very strange issue. I think for debugging it the best process would be to find the precise condition that triggers the failure. If the recipe works alone but if run in sequence with other recipes then try to taking out other recipes one by one until you find the recipe that makes this one fail. Then take that recipe and comment out resources in that recipe until it no longer fails. That way you can identify precise conditions that cause the failure. To make that task faster instead of removing every recipe one by one until the bad one shows us - remove several at once. If the group you removed seems to be the broken one then re-add the same group and remove smaller parts of that group - all until you find the smallest combination of chef resources that cause the failure.

I don't have any insight into what's causing this bug - it's very odd to me, but it seems like the Chef zero  server is having trouble writing files - this might be related to nuances of Docker filesystem that I don't understand.

**Comment by AReshma** [comment]
This is now sorted out. Thanks Juozas. As you suggested, I debugged and found the issue. In between the chef-client run, we were deleting the files inside /tmp folder, using a cleanup recipe, which was removing the client.pem of test kitchen also.
